import { type FormEvent, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Bell, ChevronLeft, ChevronRight, Settings, ShieldCheck, Trophy } from 'lucide-react'
import { Button } from '@/components/ui/Button'
import { Card, StatCard } from '@/components/ui/Card'
import { Badge } from '@/components/ui/Badge'
import { Input, PasswordInput, SearchInput, Switch } from '@/components/ui/Input'
import { ProgressBar, EmptyState } from '@/components/ui/Progress'
import { ContributorCard, LeaderboardRow, Podium } from '@/components/contributors/ContributorCard'
import { contributors, leaderboardCategories, leaderboards } from '@/data/contributors'
import { getContributorById } from '@/data/contributors'
import { contributorMetrics } from '@/data/contributorMetrics'
import { useAuth } from '@/contexts/AuthContext'
import { useUI } from '@/contexts/UIContext'

export function SimplePage({ title, description, action, href }: { title: string; description: string; action: string; href: string }) {
  return <div className="max-w-[720px] mx-auto px-4 py-24 text-center"><h1 className="font-heading text-3xl font-semibold text-text-primary">{title}</h1><p className="text-text-muted mt-3">{description}</p><Link to={href} className="inline-block mt-6"><Button>{action}</Button></Link></div>
}

export function AboutPage() {
  return <div className="max-w-[960px] mx-auto px-4 sm:px-6 py-16"><Badge variant="primary">Our approach</Badge><h1 className="font-heading text-4xl font-semibold text-text-primary mt-4">Making Web3 legible.</h1><p className="text-lg text-text-muted mt-5 max-w-2xl">EchoSpot is research infrastructure for people who need evidence before they make sense of an ecosystem.</p><div className="grid md:grid-cols-3 gap-5 mt-12">{[['Signal over spectacle','Clear, sourced research without the hype cycle.'],['Evidence first','Verification states, contributors, and sources stay visible.'],['Depth on demand','Start with a calm summary, then investigate the details.']].map(([title, body]) => <Card key={title}><h2 className="font-heading text-lg text-text-primary">{title}</h2><p className="text-sm text-text-muted mt-2">{body}</p></Card>)}</div></div>
}

export function ContributorsPage() {
  const [query, setQuery] = useState('')
  const filtered = contributors.filter((contributor) => `${contributor.name} ${contributor.username} ${contributor.skills.join(' ')}`.toLowerCase().includes(query.toLowerCase()))
  return <div className="max-w-[1280px] mx-auto px-4 sm:px-6 py-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="font-heading text-3xl font-semibold text-text-primary">Contributors</h1><p className="text-text-muted mt-2">The researchers and builders strengthening EchoSpot's public record.</p></div><Link to="/leaderboards" className="text-sm text-echo-green hover:underline">View Leaderboards</Link></div><div className="mt-7 max-w-xl"><SearchInput aria-label="Search contributors or skills" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search contributors or skills..." /></div>{filtered.length ? <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5 mt-8">{filtered.map((contributor) => <ContributorCard key={contributor.id} contributor={contributor} />)}</div> : <EmptyState title="No contributors found" description="Try a different name, handle, or skill." action={<Button variant="outline" onClick={() => setQuery('')}>Clear search</Button>} />}</div>
}

export function ContributorProfilePage() {
  const { id = '' } = useParams()
  const contributor = getContributorById(id)
  if (!contributor) return <SimplePage title="Contributor not found" description="This contributor profile is unavailable." action="View contributors" href="/contributors" />
  return <div className="max-w-[960px] mx-auto px-4 sm:px-6 py-8"><Link to="/contributors" className="inline-flex text-sm text-text-muted hover:text-echo-green"><ChevronLeft className="h-4 w-4" /> Contributors</Link><Card className="mt-5"><div className="flex flex-col sm:flex-row gap-5 sm:items-center"><img src={contributor.avatar} alt="" className="h-24 w-24 rounded-full bg-raised" /><div className="flex-1"><div className="flex flex-wrap gap-2 items-center"><h1 className="font-heading text-3xl text-text-primary">{contributor.name}</h1><Badge variant="gold">{contributor.role}</Badge></div><p className="text-text-muted">@{contributor.username}</p><p className="text-sm text-text-secondary mt-3">{contributor.bio}</p></div><Button variant="outline">Follow</Button></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-3 border-t border-border mt-6 pt-6"><StatCard label={contributorMetrics.reputation.label} value={contributor.reputation.toLocaleString()} /><StatCard label={contributorMetrics.echoPoints.label} value={contributor.echoPoints.toLocaleString()} /><StatCard label={contributorMetrics.level.label} value={contributor.level} /><Link to="/leaderboards" className="block"><StatCard label={contributorMetrics.ranking.label} value={`#${contributor.leaderboardRank}`} /></Link></div></Card><section className="mt-8"><h2 className="font-heading text-xl text-text-primary mb-4">Recent contributions</h2><Card padding="none">{contributor.contributions.map((item) => <div key={item.id} className="px-5 py-4 border-b border-border last:border-0 flex justify-between gap-3"><div><p className="text-sm text-text-primary">{item.title}</p><p className="text-xs text-text-muted mt-1">{item.type} · {item.date}</p></div><Badge variant="primary">+{item.impact}</Badge></div>)}</Card></section></div>
}

export function LeaderboardsPage() {
  const [category, setCategory] = useState<(typeof leaderboardCategories)[number]['id']>('contributors')
  const entries = leaderboards[category] ?? leaderboards.contributors
  return <div className="max-w-[960px] mx-auto px-4 sm:px-6 py-8"><div className="flex items-center gap-3"><Trophy className="h-8 w-8 text-accent-gold" /><div><h1 className="font-heading text-3xl text-text-primary">Leaderboards</h1><p className="text-text-muted mt-1">A transparent record of work and impact across the ecosystem.</p></div></div><div className="flex flex-wrap gap-2 mt-7">{leaderboardCategories.map((item) => <Button key={item.id} size="sm" variant={category === item.id ? 'primary' : 'outline'} onClick={() => setCategory(item.id)}>{item.label}</Button>)}</div><Podium entries={entries.slice(0, 3).map((item) => ({ rank: item.rank, name: item.name, avatar: item.avatar, score: item.reputation, profileId: getContributorById(item.contributorId)?.id }))} /><Card padding="none" className="mt-7">{entries.map((item) => <LeaderboardRow key={item.contributorId} {...item} profileId={getContributorById(item.contributorId)?.id} />)}</Card></div>
}

export function FounderApplicationPage() {
  const steps = [
    { title: 'Project Overview', fields: [{ name: 'projectName', label: 'Project name', placeholder: 'Aether Protocol' }, { name: 'tagline', label: 'One-sentence description', placeholder: 'Explain the project clearly' }, { name: 'chain', label: 'Primary chain', placeholder: 'Ethereum' }] },
    { title: 'Team', fields: [{ name: 'teamLead', label: 'Primary contact', placeholder: 'Name and role' }, { name: 'teamBackground', label: 'Team background', placeholder: 'Relevant experience and expertise' }, { name: 'teamLocation', label: 'Team location', placeholder: 'Remote, Lagos, London...' }] },
    { title: 'Website & Socials', fields: [{ name: 'website', label: 'Website', placeholder: 'https://example.com', type: 'url' }, { name: 'social', label: 'Primary social channel', placeholder: 'https://x.com/yourproject', type: 'url' }, { name: 'community', label: 'Community link', placeholder: 'https://discord.gg/yourproject', type: 'url' }] },
    { title: 'Whitepaper', fields: [{ name: 'whitepaper', label: 'Whitepaper or documentation URL', placeholder: 'https://docs.example.com', type: 'url' }, { name: 'repository', label: 'Repository URL', placeholder: 'https://github.com/yourproject', type: 'url' }, { name: 'technicalSummary', label: 'Technical summary', placeholder: 'Describe the core architecture' }] },
    { title: 'Product Demo', fields: [{ name: 'productStage', label: 'Current product stage', placeholder: 'MVP, testnet, mainnet...' }, { name: 'demo', label: 'Demo URL', placeholder: 'https://app.example.com', type: 'url' }, { name: 'usage', label: 'Current usage or traction', placeholder: 'Share meaningful metrics or milestones' }] },
    { title: 'Ecosystem', fields: [{ name: 'category', label: 'Project category', placeholder: 'Infrastructure, DeFi, DePIN...' }, { name: 'ecosystem', label: 'Relevant ecosystems', placeholder: 'Ethereum, Arbitrum, Solana...' }, { name: 'support', label: 'What do you need from EchoSpot?', placeholder: 'Research, verification, visibility...' }] },
    { title: 'Review & Submit', fields: [] },
  ] as const
  const [step, setStep] = useState(0)
  const [submitted, setSubmitted] = useState(false)
  const [values, setValues] = useState<Record<string, string>>({})
  const currentStep = steps[step]

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (step === steps.length - 1) {
      setSubmitted(true)
      return
    }
    setStep((value) => value + 1)
  }

  if (submitted) return <div className="max-w-[680px] mx-auto px-4 py-20"><Card className="text-center"><ShieldCheck className="h-10 w-10 text-echo-green mx-auto" /><h1 className="font-heading text-2xl text-text-primary mt-4">Application saved locally</h1><p className="text-text-muted mt-2">This frontend prototype has recorded the submission state only. No data was sent.</p><Link to="/founder" className="inline-block mt-6"><Button>Open founder console</Button></Link></Card></div>
  return <div className="max-w-[760px] mx-auto px-4 sm:px-6 py-8"><h1 className="font-heading text-3xl text-text-primary">Submit a project</h1><p className="text-text-muted mt-2">Provide the information researchers need to begin an evidence-led review.</p><div className="mt-8"><div className="flex justify-between text-xs text-text-muted mb-2"><span>Step {step + 1} of {steps.length}</span><span>{currentStep.title}</span></div><ProgressBar value={((step + 1) / steps.length) * 100} /></div><Card className="mt-6"><form onSubmit={submit}><h2 className="font-heading text-xl text-text-primary">{currentStep.title}</h2><p className="text-sm text-text-muted mt-2">All information stays in this browser session. No data is sent.</p>{currentStep.fields.length > 0 ? <div className="space-y-4 mt-6">{currentStep.fields.map((field) => <Input key={field.name} required name={field.name} label={field.label} type={'type' in field ? field.type : 'text'} placeholder={field.placeholder} value={values[field.name] ?? ''} onChange={(event) => setValues((current) => ({ ...current, [field.name]: event.target.value }))} />)}</div> : <dl className="mt-6 space-y-3 rounded-lg bg-raised border border-border p-4">{steps.slice(0, -1).map((reviewStep) => <div key={reviewStep.title} className="flex flex-col gap-1 sm:flex-row sm:items-baseline sm:justify-between"><dt className="text-sm text-text-secondary">{reviewStep.title}</dt><dd className="text-sm text-text-muted">{reviewStep.fields.some((field) => values[field.name]) ? 'Information added' : 'Not completed'}</dd></div>)}</dl>}<div className="flex justify-between gap-3 mt-8"><Button type="button" variant="ghost" disabled={step === 0} onClick={() => setStep((value) => value - 1)}>Back</Button><Button type="submit">{step === steps.length - 1 ? 'Submit application' : <>Continue <ChevronRight className="h-4 w-4" /></>}</Button></div></form></Card></div>
}

export function AuthPage({ mode }: { mode: 'login' | 'register' | 'forgot' }) {
  const { login, register } = useAuth(); const navigate = useNavigate(); const [loading, setLoading] = useState(false); const [resetRequested, setResetRequested] = useState(false); const title = mode === 'login' ? 'Welcome back' : mode === 'register' ? 'Create your account' : 'Reset your password'
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (mode === 'forgot') { setResetRequested(true); return }; setLoading(true); const form = new FormData(event.currentTarget); try { if (mode === 'login') await login(String(form.get('email')), String(form.get('password'))); else await register(String(form.get('email')), String(form.get('password')), String(form.get('name'))); navigate('/dashboard/contributor') } finally { setLoading(false) } }
  if (resetRequested) return <div role="status"><ShieldCheck className="h-10 w-10 text-echo-green" /><h1 className="font-heading text-3xl text-text-primary mt-4">Check your inbox</h1><p className="text-text-muted mt-2">If this were a connected account, reset instructions would be sent to the email you entered.</p><Button className="mt-6" onClick={() => navigate('/login')}>Back to sign in</Button></div>
  return <form onSubmit={submit}><h1 className="font-heading text-3xl text-text-primary">{title}</h1><p className="text-text-muted mt-2">{mode === 'forgot' ? 'We’ll send reset instructions to your email.' : 'Continue your evidence-led Web3 work.'}</p><div className="space-y-4 mt-8">{mode === 'register' && <Input required name="name" label="Full name" autoComplete="name" placeholder="Sarah Mitchell" />}{<Input required name="email" label="Email" type="email" autoComplete="email" placeholder="you@example.com" />}{mode !== 'forgot' && <PasswordInput required name="password" label="Password" autoComplete={mode === 'register' ? 'new-password' : 'current-password'} placeholder="••••••••" />}</div><Button type="submit" className="w-full mt-6" loading={loading}>{mode === 'login' ? 'Sign in' : mode === 'register' ? 'Create account' : 'Send reset instructions'}</Button>{mode === 'login' && <Link to="/forgot-password" className="block text-center text-sm text-echo-green mt-4">Forgot password?</Link>}<p className="text-center text-sm text-text-muted mt-6">{mode === 'login' ? <>New to EchoSpot? <Link to="/register" className="text-echo-green">Create an account</Link></> : <Link to="/login" className="text-echo-green">Back to sign in</Link>}</p></form>
}

export function SettingsPage() {
  const [emailUpdates, setEmailUpdates] = useState(true); const [security, setSecurity] = useState(true)
  return <div className="max-w-[860px] mx-auto"><div className="flex gap-3"><Settings className="h-8 w-8 text-echo-green" /><div><h1 className="font-heading text-2xl text-text-primary">Account settings</h1><p className="text-text-muted mt-1">Manage your profile, preferences, and mock connection settings.</p></div></div><div className="space-y-5 mt-8"><Card><h2 className="font-heading text-lg text-text-primary">Profile</h2><div className="grid sm:grid-cols-2 gap-4 mt-5"><Input label="Display name" defaultValue="Sarah Mitchell" /><Input label="Username" defaultValue="sarahm" /></div></Card><Card><h2 className="font-heading text-lg text-text-primary">Connected wallet</h2><p className="font-mono text-sm text-text-muted mt-3">0x742d...0bEb</p><Button variant="outline" size="sm" className="mt-4" disabled title="Wallet management is available when a wallet integration is connected">Wallet management unavailable</Button></Card><Card><h2 className="font-heading text-lg text-text-primary">Notifications</h2><div className="space-y-4 mt-5"><Switch id="research-updates" label="Research and project updates" checked={emailUpdates} onChange={setEmailUpdates} /><Switch id="security-updates" label="Security notifications" checked={security} onChange={setSecurity} /></div></Card><Card className="border-error/40"><h2 className="font-heading text-lg text-error">Danger zone</h2><p className="text-sm text-text-muted mt-2">Destructive actions are unavailable in this UI prototype.</p></Card></div></div>
}

export function ProfilePage() { const { user } = useAuth(); return <ContributorProfilePageProxy id={user?.id ?? contributors[0].id} /> }
function ContributorProfilePageProxy({ id }: { id: string }) { const contributor = getContributorById(id) ?? contributors[0]; return <div className="max-w-[960px] mx-auto"><Card><div className="flex gap-4 items-center"><img src={contributor.avatar} alt="" className="h-20 w-20 rounded-full" /><div><h1 className="font-heading text-2xl text-text-primary">{contributor.name}</h1><p className="text-text-muted">@{contributor.username} · {contributor.role}</p><p className="text-sm text-text-muted mt-2">{contributor.bio}</p></div></div></Card><div className="grid sm:grid-cols-3 gap-4 mt-5"><StatCard label="Reputation" value={contributor.reputation.toLocaleString()} /><StatCard label="Contributions" value={contributor.contributions.length} /><StatCard label="Projects followed" value="14" /></div></div> }

export function NotificationsPage() { const { notifications, markAllNotificationsRead, markNotificationRead } = useUI(); const navigate = useNavigate(); return <div className="max-w-[820px] mx-auto"><div className="flex justify-between gap-4 items-center"><div><h1 className="font-heading text-2xl text-text-primary">Notifications</h1><p className="text-text-muted mt-1">Recent platform activity and research updates.</p></div><Button variant="outline" size="sm" onClick={markAllNotificationsRead}>Mark all read</Button></div><Card padding="none" className="mt-7">{notifications.map((notice) => <button key={notice.id} onClick={() => { markNotificationRead(notice.id); if (notice.link) navigate(notice.link) }} className="w-full text-left px-5 py-4 border-b border-border last:border-0 hover:bg-raised transition-colors"><div className="flex gap-3"><Bell className={`h-5 w-5 shrink-0 ${notice.read ? 'text-text-muted' : 'text-echo-green'}`} /><div className="flex-1"><p className="text-sm text-text-primary">{notice.title}</p><p className="text-sm text-text-muted mt-1">{notice.message}</p><p className="text-xs text-text-muted mt-2">{notice.timestamp}</p></div>{!notice.read && <span className="h-2 w-2 rounded-full bg-echo-green" />}</div></button>)}</Card></div> }
